trigger:
  branches:
    include: ['feature/*']
  paths:
    include: ['src/azureapp/']

name: 'prepare-management-infrastructure'
variables:
  environment: 'management'
  stage: 'truehhart'
  subscriptionName: 'main'
  appName: 'azureapp'
  location: 'westeurope'

stages:
- stage: 'prepare_infrastructure'
  jobs: 
  - job: 'deploy_azure_resources'
    pool: localhost
    steps:
      - task: AzureResourceGroupDeployment@2
        displayName: '[Azure] Deploy ResourceGroup'
        inputs:
          ConnectedServiceName: '$(subscriptionName)-sc'
          azureSubscription: '$(subscriptionName)'
          resourceGroupName: '$(environment)-$(stage)-rg'
          location: '$(location)'
          csmFile:  '$(Build.Repository.LocalPath)/infrastructure/resourceDefinitions/azureResourceGroup.json'
          overrideParameters: '-environment "$(environment)" -stage "$(stage)" -location $(location)'

      - task: AzureResourceGroupDeployment@2
        displayName: '[Azure] Deploy ContainerRegistry'
        inputs:
          ConnectedServiceName: '$(subscriptionName)-sc'
          azureSubscription: '$(subscriptionName)'
          resourceGroupName: '$(environment)-$(stage)-rg'
          location: '$(location)'
          csmFile:  '$(Build.Repository.LocalPath)/infrastructure/resourceDefinitions/azureResourceGroup.json'
          overrideParameters: '-environment "$(environment)" -stage "$(stage)" -location $(location)'