# This job should be run one time only.
# You could create management environment using az cli like I used to in my previous revisions,
#   but since AzPipelines allow you to trigger ARM deployments on their end - why not use them instead.
trigger: ['none']

name: 'prepare-management-infrastructure'
variables:
  vmImage: 'ubuntu-latest'
  environment: 'management'
  stage: 'truehhart'
  subscriptionName: 'main'
  appName: 'azureapp'
  location: 'westeurope'

stages:
# This pipeline deploys the only needed infrastructure for the project:
# - The management resource group.
# - The management container registry.
# These resources will be reused across the project to host the app that's built.
- stage: 'prepare_infrastructure'
  displayName: 'Deploying Management Infrastructure'
  jobs:
  - job: 'deploy_azure_resources'
    displayName: 'Deploying Azure Resources'
    pool:
      vmImage: $(vmImage)
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: '[Azure] Deploying ${{ variables.environment }}-${{ variables.stage }} ContainerRegistry'
        inputs:
          deploymentScope: 'Resource Group'
          templateLocation: 'Linked artifact'
          csmFile:  '$(Build.Repository.LocalPath)/infrastructure/resourceDefinitions/azureContainerRegistry.json'
          ConnectedServiceName: '$(subscriptionName)-sc'
          resourceGroupName: '$(environment)-$(stage)-rg'
          location: '$(location)'
          overrideParameters: '-environment "$(environment)" -stage "$(stage)" -location $(location)'