trigger:
  branches:
    include: ['feature/*']
  paths:
    include: ['src/azureapp/']

name: 'prepare-management-infrastructure'
variables:
  environment: 'management'
  stage: 'truehhart'
  subscriptionName: 'main'
  appName: 'azureapp'
  location: 'westeurope'

stages:
# This pipeline deploys the only needed infrastructure for the project:
# - The management resource group.
# - The management container registry.
# These resources will be reused across the project to host the app that's built.
- stage: 'prepare_infrastructure'
  displayName: 'Deploying Management Infrastructure'
  jobs: 
  - job: 'deploy_azure_resources'
    pool: localhost
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: '[Azure] Deploying ResourceGroup'
        inputs:
          deploymentScope: 'Subscription'
          templateLocation: 'Linked artifact'
          csmFile:  '$(Build.Repository.LocalPath)/infrastructure/resourceDefinitions/azureResourceGroup.json'
          ConnectedServiceName: '$(subscriptionName)-sc'
          location: '$(location)'
          overrideParameters: '-environment "$(environment)" -stage "$(stage)" -location $(location)'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: '[Azure] Deploying ContainerRegistry'
        inputs:
          deploymentScope: 'Resource Group'
          templateLocation: 'Linked artifact'
          csmFile:  '$(Build.Repository.LocalPath)/infrastructure/resourceDefinitions/azureContainerRegistry.json'
          ConnectedServiceName: '$(subscriptionName)-sc'
          resourceGroupName: '$(environment)-$(stage)-rg'
          location: '$(location)'